import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styled from "styled-components";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Asdf>안녕하세요</Asdf>
    </>
  );
}
const Asdf = styled.div`
  background-color: ${(props) => props.theme.colors.main.blue};
  width: 100px;
  height: 100px;
`;
